services:

  nginx:
    image: nginx:latest
    #ВАЖНО: указать переменные из темплейта
    command: /bin/bash -c "envsubst '$${DOMAIN} $${FRONT_UPSTREAM} $${BILLING_UPSTREAM}' \
      < /etc/nginx/conf.d/default.conf.template \
      > /etc/nginx/conf.d/default.conf \
      && nginx -g 'daemon off;'"
    env_file:
      - .env
    volumes:
      # Это темплейт, и он будет перзаписан в /etc/nginx/conf.d/default.conf
      - ./nginx/nginx.tmpl.conf:/etc/nginx/conf.d/default.conf.template
    environment:
      TZ: Europe/Moscow
    ports:
      - "80:80"
      - "8080:80"
      - "443:443"
    restart: always

  backend:
    build:
      context: ./java-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      server.port: 8090
      management.server.port: 9090
      server.domain: localhost
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9090/actuator/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    restart: always
