[project]
name = "python-backend"
version = "0.1.0"
description = "Python backend for faas billing"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "uvicorn>=0.37.0",
]
