spring:
  application:
    name: spring-billing-backend

server:
  port: 8091
  domain: ${DOMAIN:localhost:8091}
  servlet:
    context-path: /api/billing

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
    urls:
      - name: ${server.domain}
        display-name: server domain
        url: http://${server.domain}${server.servlet.context-path}/v3/api-docs