spring:
  application:
    name: spring-billing-backend

server:
  port: 8091
  domain: http://localhost:8091
  servlet:
    context-path: /api/billing

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 9090

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger
    urls:
      - name: ${server.domain}
        display-name: server domain ${server.domain}
        url: ${server.domain}${server.servlet.context-path}/v3/api-docs

jwt:
  cookie:
    name: JWT_TOKEN
  signing:
    key: example-jwt-token-signing-key-with-width-more-then-256-bit

cors:
  allowed:
    origins: localhost:5173