name: Build image
on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  create_tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short commit hash
        id: git_short_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Create Tag
        id: create_tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ steps.git_short_hash.outputs.hash }}
